const $=s=>document.querySelector(s);const content=$('#content');let token=sessionStorage.getItem('mh_dashboard_token')||'';const titles={overview:'Vue générale',members:'Membres',tickets:'Tickets',moderation:'Modération',giveaways:'Giveaways',ptero:'Pterodactyl',logs:'Audit logs'};
async function api(path,opt={}){const r=await fetch('/api/dashboard'+path,{...opt,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(r.status===401)throw Error('UNAUTHORIZED');if(!r.ok)throw Error(d.error||'Erreur API');return d}
function card(label,value){return `<div class="stat"><span class="muted">${label}</span><b>${value??'—'}</b></div>`}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(page='overview'){ $('#title').textContent=titles[page];try{if(page==='overview'){const d=await api('/overview');content.innerHTML=`<div class="grid">${card('Bot',d.bot?.online?'🟢 En ligne':'🔴 Hors ligne')}${card('Serveurs Discord',d.guilds)}${card('Membres',d.members)}${card('Tickets ouverts',d.tickets)}${card('Commandes',d.commands)}${card('Avertissements',d.warns)}</div><div class="panel" style="margin-top:16px"><h2>Services</h2><p>Discord : <b class="ok">${d.bot?.online?'OK':'OFF'}</b></p><p>Pterodactyl : <b>${d.ptero?'🟢 Connecté':'⚪ Non configuré'}</b></p><p>API : <b class="ok">OK</b></p></div>`}
else if(page==='logs'){const d=await api('/logs');content.innerHTML=`<div class="panel"><h2>Dernières actions</h2><table class="table"><thead><tr><th>Date</th><th>Action</th><th>Utilisateur</th><th>Détails</th></tr></thead><tbody>${d.logs.map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.action)}</td><td>${esc(x.user)}</td><td>${esc(x.details)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Aucun log</td></tr>'}</tbody></table></div>`}
else if(page==='moderation'){const d=await api('/moderation');content.innerHTML=`<div class="grid">${card('Avertissements',d.warns)}${card('Bans',d.bans)}${card('Expulsions',d.kicks)}</div><div class="panel" style="margin-top:16px"><h2>Actions</h2><p class="muted">Les actions sensibles sont volontairement exécutées côté serveur après contrôle des permissions.</p></div>`}
else if(page==='members'){const d=await api('/members');content.innerHTML=`<div class="panel"><h2>Membres</h2><table class="table"><thead><tr><th>Membre</th><th>ID</th><th>Rôles</th></tr></thead><tbody>${d.members.map(x=>`<tr><td>${esc(x.tag)}</td><td>${esc(x.id)}</td><td>${esc(x.roles)}</td></tr>`).join('')}</tbody></table></div>`}
else if(page==='tickets'){const d=await api('/tickets');content.innerHTML=`<div class="panel"><h2>Tickets ouverts</h2><table class="table"><thead><tr><th>Salon</th><th>Propriétaire</th><th>Assigné</th></tr></thead><tbody>${d.tickets.map(x=>`<tr><td>${esc(x.channel_id)}</td><td>${esc(x.owner_id)}</td><td>${esc(x.assigned_to||'—')}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">Aucun ticket</td></tr>'}</tbody></table></div>`}
else if(page==='giveaways'){const d=await api('/giveaways');content.innerHTML=`<div class="panel"><h2>Giveaways</h2><table class="table"><thead><tr><th>Récompense</th><th>Gagnants</th><th>Fin</th><th>Statut</th></tr></thead><tbody>${d.giveaways.map(x=>`<tr><td>${esc(x.prize)}</td><td>${x.winner_count}</td><td>${new Date(x.ends_at).toLocaleString('fr-FR')}</td><td>${x.ended?'Terminé':'Actif'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Aucun giveaway</td></tr>'}</tbody></table></div>`}
else if(page==='ptero'){const d=await api('/ptero');content.innerHTML=`<div class="grid">${card('Connexion',d.connected?'🟢 OK':'⚪ Non configuré')}${card('Serveurs',d.servers??0)}${card('Nœuds',d.nodes??0)}</div><div class="panel" style="margin-top:16px"><p class="muted">La clé Pterodactyl reste uniquement sur le serveur. Elle n'est jamais envoyée au navigateur.</p></div>`}}
catch(e){if(e.message==='UNAUTHORIZED'){sessionStorage.removeItem('mh_dashboard_token');token='';showLogin();return}content.innerHTML=`<div class="panel"><h2>Erreur</h2><p class="bad">${esc(e.message)}</p></div>`}}
function showLogin(){$('#login').hidden=false;$('#app').hidden=true}function showApp(){$('#login').hidden=true;$('#app').hidden=false;load()}
$('#loginBtn').onclick=async()=>{const v=$('#token').value.trim();if(!v)return;token=v;try{await api('/overview');sessionStorage.setItem('mh_dashboard_token',token);showApp()}catch{$('#loginError').textContent='Clé invalide ou dashboard désactivé.'}};
$('#logout').onclick=()=>{sessionStorage.removeItem('mh_dashboard_token');token='';showLogin()};$('#refresh').onclick=()=>load(document.querySelector('nav button.active')?.dataset.page||'overview');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');load(b.dataset.page)});if(token)showApp();
